# Generated by Django 5.0.1 on 2026-04-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymprogram',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gym Program', 'verbose_name_plural': 'Gym Programs'},
        ),
        migrations.RemoveConstraint(
            model_name='gymprogram',
            name='duration_days_gt_0',
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='benefits',
            field=models.TextField(blank=True, help_text='Enter benefits, one per line (press Enter after each benefit)', null=True),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='code',
            field=models.CharField(choices=[('weight_loss', '⚖️ Weight Loss'), ('muscle_gain', '💪 Muscle Gain'), ('boxing', '🥊 Boxing'), ('crossfit', '🏋️ CrossFit'), ('personal_training', '👨\u200d🏫 Personal Training'), ('women_fitness', '👩\u200d🦰 Women Fitness'), ('teen_fitness', '🧒 Teen Fitness')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='price_uzs',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='requirements',
            field=models.TextField(blank=True, help_text='Enter requirements, one per line (press Enter after each requirement)', null=True),
        ),
        migrations.AlterField(
            model_name='gymprogram',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='users.trainer'),
        ),
    ]
