# Generated by Django 5.0.1 on 2026-04-10 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('gym', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('aloqa', 'Aloqa Bank'), ('sqb', 'SQB Bank'), ('visa', 'Visa'), ('mastercard', 'Master Card')], max_length=100)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Card',
                'verbose_name_plural': 'Payment Cards',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', "Karta orqali to'lash"), ('click', "Click orqali to'lash"), ('payme', "Payme orqali to'lash"), ('uzum', "Uzum orqali to'lash")], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount_uzs', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('max_amount_uzs', models.DecimalField(decimal_places=2, default=100000000, max_digits=12)),
                ('min_amount_usd', models.DecimalField(decimal_places=2, default=0.1, max_digits=12)),
                ('max_amount_usd', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('usd_to_uzs', models.DecimalField(decimal_places=2, default=12000, help_text='1 USD = X UZS', max_digits=10)),
                ('payment_timeout_hours', models.IntegerField(default=24, help_text="Soat ichida to'lash kerak")),
                ('send_email_on_payment', models.BooleanField(default=True)),
                ('send_telegram_notification', models.BooleanField(default=True)),
                ('fake_detection_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('payment_type', models.CharField(choices=[('program', "Kursga to'lash"), ('membership', "Membership to'lashi"), ('coaching', 'Coach bilan sessiya')], max_length=50)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)])),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda 🕐'), ('processing', 'Qayta ishlanmoqda 🔄'), ('approved', 'Tasdiqlandi ✅'), ('rejected', 'Rad etildi ❌'), ('cancelled', 'Bekor qilindi 🚫'), ('refund', 'Qaytarma 💰')], db_index=True, default='pending', max_length=20)),
                ('screenshot', models.ImageField(upload_to='payments/%Y/%m/%d/')),
                ('screenshot_verified', models.BooleanField(default=False)),
                ('is_fake_detected', models.BooleanField(default=False)),
                ('fake_reason', models.TextField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Payment method commission', max_digits=12)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after commission', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approvals', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='enrollments.enrollment')),
                ('membership_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_payments', to='gym.membershipplan')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_payments', to='gym.gymprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to='users.telegramuser')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentcard')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_payment', 'Can approve payments'), ('can_reject_payment', 'Can reject payments'), ('can_refund_payment', 'Can refund payments')],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', "To'lov yaratildi"), ('screenshot_uploaded', 'Screenshot yuklandi'), ('under_review', 'Tekshiruvda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('refund_initiated', 'Qaytarma boshlandi')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('user_request', "Foydalanuvchi so'rovi"), ('duplicate', "Nusxa to'lov"), ('fraud', "Firibgar to'lov"), ('system_error', 'Sistema xatosi'), ('no_show', "Dars o'tkazdi")], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Tamamlandi'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_initiations', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_record', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'status'], name='payments_pa_payment_05904b_idx'),
        ),
    ]
